version: '3.8'

services:

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CrudUsuarios;User Id=sa;Password=Password123!;TrustServerCertificate=True

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"